### ISSUE TITLE
Watched Settings Description

### ISSUE THREAD

**Issue by PrestonGiorgianni** [Azure/AppConfiguration-JavaScriptProvider#63]
Based on the description of this setting, I was expecting the package to watch for changes.

![Screenshot 2024-05-14 at 2 17 22 PM](https://github.com/Azure/AppConfiguration-JavaScriptProvider/assets/61525781/4e32aff6-baf6-4ed1-8289-bde18839671c)

When I was writing code, it seems I have to call refresh on a regular basis to check for any changes.

Is this the expected behavior?

**Comment by Eskibear** [comment]
yes, it's the expected behavior. You can decide when to call refresh() on your own. Taking a web app for example, it's recommended to be event-driven, calling refresh() when a request comes in, which would save quota. Of course you can also simply polling changes by calling refresh() with a fixed interval... It's totally up to you.

**Comment by Eskibear** [comment]
Maybe change the description as below, does it look clearer?

> Any modification to watched settings will refresh all setting loaded by the configuration provider **when refresh() is called**.

**Comment by PrestonGiorgianni** [comment]
That would make it very clear what this setting does. I love the idea

**Comment by Eskibear** [comment]
@PrestonGiorgianni  We recently updated the docs for dynamic configuration, hope it helps as well.
https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-javascript?tabs=configuration-map

**Comment by PrestonGiorgianni** [comment]
@Eskibear Thank you
